FROM mambaorg/micromamba:0.19.1
COPY --chown=micromamba:micromamba linux.yml /tmp/linux.yml
COPY . /
USER root
RUN apt-get update -y
RUN apt-get install libgl1-mesa-glx -y
USER 1000
RUN micromamba install -y -n base -f /tmp/linux.yml && micromamba clean --all --yes
WORKDIR /
CMD ['cd /']
ARG MAMBA_DOCKERFILE_ACTIVATE=1
CMD ['conda list']
RUN python interfaz.py