name: pySRM
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8
 - pyqt=5.12
 - rasterio
 - fiona
 - matplotlib
 - pandas
 - xarray
 - scipy
 - rioxarray
 - geopandas
 - statsmodels
 - pmdarima
 - pip:
   - dask-geopandas
   - hydroeval
   - qt_material
   - pyqt5-tools
   - pyqt5-sip
   - pyqtwebengine